DROP TABLE IF EXISTS @cdmDatabaseSchema.PERSON  cascade;
DROP TABLE IF EXISTS @cdmDatabaseSchema.OBSERVATION_PERIOD cascade;
DROP TABLE IF EXISTS @cdmDatabaseSchema.VISIT_OCCURRENCE  cascade;
DROP TABLE IF EXISTS @cdmDatabaseSchema.VISIT_OCCURRENCE2  cascade;


DROP TABLE IF EXISTS @cdmDatabaseSchema.VISIT_DETAIL  cascade;
DROP TABLE IF EXISTS @cdmDatabaseSchema.CONDITION_OCCURRENCE  cascade;
DROP TABLE IF EXISTS @cdmDatabaseSchema.DRUG_EXPOSURE cascade;
DROP TABLE IF EXISTS @cdmDatabaseSchema.PROCEDURE_OCCURRENCE cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.DEVICE_EXPOSURE cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.MEASUREMENT cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.OBSERVATION cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.DEATH cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.NOTE cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.NOTE_NLP cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.SPECIMEN cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.FACT_RELATIONSHIP cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.LOCATION cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.CARE_SITE cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.PROVIDER cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.PAYER_PLAN_PERIOD cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.COST cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.DRUG_ERA cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.DOSE_ERA cascade;

 
DROP TABLE IF EXISTS @cdmDatabaseSchema.CONDITION_ERA cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.METADATA cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.CDM_SOURCE cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.CONCEPT cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.VOCABULARY cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.DOMAIN cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.CONCEPT_CLASS cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.CONCEPT_RELATIONSHIP cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.RELATIONSHIP cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.CONCEPT_SYNONYM cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.CONCEPT_ANCESTOR cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.SOURCE_TO_CONCEPT_MAP cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.DRUG_STRENGTH cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.COHORT_DEFINITION cascade;

--HINT DISTRIBUTE ON RANDOM
DROP TABLE IF EXISTS @cdmDatabaseSchema.ATTRIBUTE_DEFINITION cascade;